import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core'

// Drizzle schema for schools table
// NOTE: This schema should stay in sync with the Zod SchoolSchema in src/schema.ts
export const schools = sqliteTable('schools', {
  _id: integer('_id').primaryKey(),
  School_Id: text('School_Id').notNull(),
  Org_Name: text('Org_Name').notNull(),
  Telephone: text('Telephone'),
  Fax: text('Fax'),
  Email: text('Email'),
  Contact1_Name: text('Contact1_Name'),
  URL: text('URL'),
  Add1_Line1: text('Add1_Line1'),
  Add1_Suburb: text('Add1_Suburb'),
  Add1_City: text('Add1_City'),
  Add2_Line1: text('Add2_Line1'),
  Add2_Suburb: text('Add2_Suburb'),
  Add2_City: text('Add2_City'),
  Add2_Postal_Code: text('Add2_Postal_Code'),
  Urban_Rural_Indicator: text('Urban_Rural_Indicator'),
  Org_Type: text('Org_Type'),
  Definition: text('Definition'),
  Authority: text('Authority'),
  School_Donations: text('School_Donations'),
  CoEd_Status: text('CoEd_Status'),
  KMEPeakBody: text('KMEPeakBody'),
  Takiwā: text('Takiwā'),
  Territorial_Authority: text('Territorial_Authority'),
  Regional_Council: text('Regional_Council'),
  Local_Office_Name: text('Local_Office_Name'),
  Education_Region: text('Education_Region'),
  General_Electorate: text('General_Electorate'),
  Māori_Electorate: text('Māori_Electorate'),
  Statistical_Area_2_Code: text('Statistical_Area_2_Code'),
  Statistical_Area_2_Description: text('Statistical_Area_2_Description'),
  Ward: text('Ward'),
  Col_Id: text('Col_Id'),
  Col_Name: text('Col_Name'),
  Latitude: real('Latitude'),
  Longitude: real('Longitude'),
  Enrolment_Scheme: text('Enrolment_Scheme'),
  EQi_Index: text('EQi_Index'),
  Roll_Date: text('Roll_Date'),
  Total: integer('Total'),
  European: integer('European'),
  Māori: integer('Māori'),
  Pacific: integer('Pacific'),
  Asian: integer('Asian'),
  MELAA: integer('MELAA'),
  Other: integer('Other'),
  International: integer('International'),
  Isolation_Index: text('Isolation_Index'),
  Language_of_Instruction: text('Language_of_Instruction'),
  BoardingFacilities: text('BoardingFacilities'),
  CohortEntry: text('CohortEntry'),
  Status: text('Status'),
  DateSchoolOpened: text('DateSchoolOpened'),
  created_at: integer('created_at', { mode: 'timestamp' }).$defaultFn(() => new Date()),
  updated_at: integer('updated_at', { mode: 'timestamp' }).$defaultFn(() => new Date())
})

export const cacheMetadata = sqliteTable('cache_metadata', {
  id: integer('id').primaryKey(),
  cache_key: text('cache_key').unique().notNull(),
  last_updated: integer('last_updated', { mode: 'timestamp' }).notNull(),
  record_count: integer('record_count').notNull()
})